### PR TITLE
[image-build] Added PR merge

### PR DESCRIPTION
**Pull request by papagalu**
- now the scripts checks the following env vars:
        + JOB_TYPE
        + PULL_NUMBER

    if the job type is presubmit, the script will merge the PR into master branch
and will test building the images
    if the job type is postsubmit, the script will build master and push the built
images

### CODE REVIEW

**Comment by papagalu** [comment]
@adelina-t please review

**Comment by test-e2e-win** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/e2e-win/e2e-win-prow-deployment/pull/12#issuecomment-406194224" title="Approved">adelina-t</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/e2e-win/e2e-win-prow-deployment/blob/master/OWNERS)~~ [adelina-t]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by test-e2e-win** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/e2e-win/e2e-win-prow-deployment/pull/12#issuecomment-406194224" title="Approved">adelina-t</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/e2e-win/e2e-win-prow-deployment/blob/master/OWNERS)~~ [adelina-t]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
